name: Update README

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - uses: actions/checkout@v4.2.2
      
      - uses: actions/checkout@v3
      
      - uses: jamesgeorge007/github-activity-readme@master

      - uses: Readme-Workflows/recent-activity@v2.4.1
     env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "Specify a custom commit message"
          MAX_LINES: 10
          COMMIT_NAME: GitHub Activity Readme
          COMMIT_EMAIL: github-actions[bot]@users.noreply.github.com

